### PR TITLE
Added EOS Amsterdam April report

### PR DESCRIPTION
**Pull request by yannickeosams**

### CODE REVIEW

**Review by rakeden — CHANGES_REQUESTED** [review]
Thanks for your report submission!

Please submit your latest report inside the file latest.md!

Additional information on the current submission process can be found here: https://github.com/wax-office-of-inspector-general/waxguilds/issues/925

**Comment by rakeden** [comment]
@yannickeosams

**Comment by rakeden** [comment]
Sorry @yannickeosams, but this still wrong. Your latest report should be done as `latest.md` file inside your guilds folder.
Going forward you will only modify this file for your latest report

**Comment by yannickeosams** [comment]
@rakeden Now it should all be good and the latest.md file in our folder contains our May update (in the correct template)!

**Pull request merged**
